0630_윤석훈_디자인.xd
SinaGram-DSM/Tasting pull request #20
Opened 2020-06-30 04:18 UTC by seockhun

2020-06-30 05:28 UTC, MinSeoGi requested changes
양식에 맞춰서 제목 다시 써주세요! 😢

2020-06-30 23:45 UTC, zzelcyy approved these changes

2020-07-01 03:57 UTC, MinSeoGi approved these changes
수고하셨습니다~

2020-07-01 08:08 UTC, DAEUN28 approved these changes
색조합 느낌있네요~!

2020-07-03 03:02 UTC, merged