0630_윤준기_디자인.xd
SinaGram-DSM/Tasting pull request #26
Opened 2020-06-30 12:51 UTC by junkiYoon

2020-06-30 23:47 UTC, zzelcyy approved these changes
양식에 맞게 작성해 주세요!

2020-06-30 23:47 UTC, zzelcyy requested changes
양식에 맞게 작성해 주세요!

2020-07-01 00:49 UTC, zzelcyy approved these changes

2020-07-01 07:54 UTC, MinSeoGi approved these changes
오... 디자인에 뭔가 준기 친구만의 느낌이 있네요!
수고하셨습니다!👏👏👏

2020-07-01 08:04 UTC, DAEUN28 approved these changes
심플이즈베스트~!~!

2020-07-01 10:33 UTC, merged