1412_윤석훈_안드
SinaGram-DSM/Tasting pull request #28
Opened 2020-07-03 10:17 UTC by seockhun

2020-07-03 10:27 UTC, MinSeoGi approved these changes

2020-07-03 11:14 UTC, zzelcyy requested changes
PR 제목 양식에 맞게 작성해 주세요!

2020-07-04 09:01 UTC, DAEUN28 approved these changes

2020-07-05 12:33 UTC, zzelcyy approved these changes

2020-07-06 01:18 UTC, merged