[박동행] 백엔드 과제 제출
SinaGram-DSM/Tasting pull request #34
Opened 2020-07-06 09:13 UTC by Donghaeng

2020-07-06 12:59 UTC, seungbin9850 approved these changes

2020-07-06 13:47 UTC, MinSeoGi requested changes
수정할게 좀 있습니다....😭😭
1. 안드로이드 파일이 함께 올려짐
2. 백엔드 PR 양식에 맞지 않음 (Tasting/Homework/05_백엔드/README.md 참고)

2020-07-07 01:24 UTC, seungbin9850 reviewed
안드파일 지워주세요...

2020-07-07 01:29 UTC, seungbin9850 requested changes
안드파일 지워주세요..

2020-07-07 04:20 UTC, closed without merging