[윤준기] 프론트 과제 제출
SinaGram-DSM/Tasting pull request #35
Opened 2020-07-06 13:20 UTC by junkiYoon

2020-07-06 13:36 UTC, MinSeoGi requested changes
시나그램 깃허브/Tasting/Homework/04_프론트엔드/README.md 파일 읽고 다시 PR 보내주세요!

2020-07-07 02:15 UTC, MinSeoGi approved these changes
👏👏👏👏 💯👍

2020-07-07 07:01 UTC, dong030303 approved these changes

2020-07-07 11:52 UTC, S-rim approved these changes

2020-07-07 23:32 UTC, fldfls approved these changes

2020-07-09 01:31 UTC, merged