[최아연] 프론트 과제 제출
SinaGram-DSM/Tasting pull request #37
Opened 2020-07-07 05:32 UTC by AHYEON04

2020-07-07 07:00 UTC, dong030303 approved these changes

2020-07-07 10:37 UTC, MinSeoGi requested changes
Tasting/Homework/04_프론트엔드/README.md 읽고 다시 PR 요청해주세요!ㅠ
그리구 저번에 이미 머지한 My Page 폴더는 모두 삭제 부탁드립니당...

2020-07-09 13:41 UTC, YeYerin approved these changes

2020-07-10 05:09 UTC, fldfls approved these changes

2020-07-12 14:21 UTC, S-rim approved these changes

2023-01-25 09:30 UTC, closed without merging