자기소개페이지계획
SinaGram-DSM/Tasting pull request #5
Opened 2020-06-23 13:07 UTC by yejin463

과제 제출합니다.

2020-06-23 13:39 UTC, DAEUN28 reviewed
급하게 하느라 형식을 제대로 못적은 것 같아요ㅠㅜㅠㅜ 
[과제안내](https://github.com/SinaGram-DSM/Tasting/blob/master/OT/200618과제.md)대로 수정해주세용!!

2020-06-23 23:25 UTC, DAEUN28 approved these changes
인사최고🥰

2020-06-23 23:26 UTC, MinSeoGi approved these changes
정말 멋진 취미를 가지셨네용 😆😆

2020-06-24 00:33 UTC, S-rim approved these changes
아 파스텔톤 뭘 좀 아는 친구네요😝

2020-06-24 02:28 UTC, zzelcyy requested changes
저도 사람 만나는 것 좋아해요 ㅎㅎㅎ 그런데 파일 확장자가 txt네요 ㅠㅠ md로 올려 주세요!!

2020-06-24 07:27 UTC, zzelcyy approved these changes

2020-06-26 03:21 UTC, merged